
import { Geist, Geist_Mono, Rubik } from "next/font/google";
import "./globals.css";
import { ReactLenis } from './utils/lenis/lenis'

const globalFont = Rubik({
  subsets: ['latin', 'cyrillic', 'cyrillic-ext'],
  variants: ['400'],

})

export const metadata = {
  title: "File Star",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body
          className={`${globalFont.className}`}

        >
          {children}
        </body>
      </ReactLenis>

    </html>
  );
}
